persistence:
  storageClass: 'manual'
  namespace: 'default'
  kafka:
    hostPath: '/kafka'
  zookepeer:
    hostPath: '/zookeeper'

services:
  kafka:
    nodePort:
      port: 30002

kafka:
  externalAccess:
    enabled: true
    service:
      type: NodePort
      nodePorts:
        - 30001
  advertisedListeners:
    - "INTERNAL://:9093"
    - "CLIENT://:9092"
    - "EXTERNAL://192.168.122.106:30001"